version: "3"

# use mariadb instead of mysql due to wider platform support

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_DATABASE: squint
      MARIADB_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    ports:
      - 3306:3306
